### ISSUE TITLE
3-2 キス島沖 出現アイテムのミス | 3-2 wrong resource icon

### ISSUE THREAD

**Issue by Tibowl** [Tibowl/KCBugTracker#2]
**Description**
3-2 (キス島沖) start screen still shows steel icon while the map gives ammo. This issue got introduced with the phase 2 map rework.

**Screenshot and/or video**
![start screen](https://user-images.githubusercontent.com/5676386/88920986-0deb9580-d26e-11ea-8d35-70c8ddb020da.png)
![resource node](https://user-images.githubusercontent.com/5676386/88920996-117f1c80-d26e-11ea-83b7-6ebdac091458.png)

**Reproducing**
Steps to reproduce the behavior: (if applicable, otherwise remove this section)
1. Go to 3-2, see start screen
2. Sortie a single scrap DD with damecon equipped, go to B node
3. You get ammo while start screen has steel listed

**Potential fix**
Change the icon to ammo on start screen - this can be done from api_start2/getData under api_mst_mapinfo in api_item of 32. 
![image](https://user-images.githubusercontent.com/5676386/88921157-5440f480-d26e-11ea-9659-a4d5e111afaf.png)

**Comment by Ryuuen** [comment]
Japanese Translation:

タイトル：3-2 キス島沖 出現アイテムのミス

**説明**
3-2 (キス島沖)の紹介ページでは、鋼材の獲得が可能になっていますが、獲得可能なのは弾薬です。
この現象はPhase2のマップ修正から現れます。

**スクリーンショット及び動画**
![start screen](https://user-images.githubusercontent.com/5676386/88920986-0deb9580-d26e-11ea-8d35-70c8ddb020da.png)
![resource node](https://user-images.githubusercontent.com/5676386/88920996-117f1c80-d26e-11ea-83b7-6ebdac091458.png)

**バグの再現方法**
バグを再現するために、必要な手順を説明してください：（存在しない場合は削除しても良い）
1.  3-2の紹介ページに移動する
2. 応急修理要員を装備する駆逐艦を出撃させ、Bマスに行く
3. 紹介ページには鋼材なのに弾薬を獲得する

**可能な修正方法**
画面上の鋼材アイコンを弾薬アイコンに修正します。api_mst_mapinfo配下のapi_start2/getDataに、32のapi_itemで修正できます。
![image](https://user-images.githubusercontent.com/5676386/88921157-5440f480-d26e-11ea-9659-a4d5e111afaf.png)

**Comment by Tibowl** [comment]
Fixed as of 2020-08-27
