### ISSUE TITLE
明石の改修工廠 メニューバグ | Akashi improvement menu bug

### ISSUE THREAD

**Issue by Tibowl** [Tibowl/KCBugTracker#34]
**Description**
When improving the middle equipment, the top equipment can be brought in by clicking on top of the screen (near username). After selecting a specific equipment and going back to the 3 equipment screen, the middle will still have the improve UI.

**Screenshot and/or video**
![image](https://user-images.githubusercontent.com/5676386/89104072-d1a76900-d416-11ea-87e2-1359daaa9813.png)

**Reproducing**
Steps to reproduce the behavior: (if applicable, otherwise remove this section)
1. Open Akashi improvement screen
2. Click on middle one and select a equipment
3. Click near username
4. Select an equipment
5. Press back button on this top equipment
6. See bug

**Fix**
In `TaskTop` in function `_CenteringBox`, for the middle case change `_topView.revampRecipeBox[0].position['y'] = -111,` to `_topView.revampRecipeBox[0].position['y'] = -200,` so the box appears completely offscreen.

Source: [Twitter - myteaGuard](https://twitter.com/myteaGuard/status/1144526567114076161)

**Comment by kaedec-adm** [comment]
**Japanese Translation:**
タイトル：明石の改修工廠 メニューバグ

**説明**
中段の装備を改修するとき、画面上部(提督名付近)をクリックすることで上段の装備を画面中央に持ってくることができてしまう。特定の装備を選択して3段の画面に戻っても、中段は改修UIのままである。

**スクリーンショット及び動画**
![image](https://user-images.githubusercontent.com/5676386/89104072-d1a76900-d416-11ea-87e2-1359daaa9813.png)

**バグの再現方法**
バグを再現するために、必要な手順を説明してください：（存在しない場合は削除しても良い）

1. 明石の改修工廠画面を開く
2. 中段をクリックして装備の1つを選択する
3. 提督名付近をクリックする
4. 装備を選択する
5. 上段の装備の戻るボタンをクリックして戻る
6. バグの再現

**修正**
`_CenteringBox`関数中の`TaskTop`を、中段の場合`_topView.revampRecipeBox[0].position['y'] = -111,`から`_topView.revampRecipeBox[0].position['y'] = -200,`にすると、上段は完全に画面外に移動するようになる。

ソース: [Twitter - myteaGuard](https://twitter.com/myteaGuard/status/1144526567114076161)

**Comment by Tibowl** [comment]
Fixed as of 2022-01-21
