### ISSUE TITLE
ASW bonuses from modernization of Kaga Kai Ni Go will preserve after remodel, causes unexpected ASW behaviour

### ISSUE THREAD

**Issue by axmmisaka** [Tibowl/KCBugTracker#39]
**Description**
ASW bonuses from modernization of Kaga Kai Ni Go will preserve after further remodeling, namely to Kaga Kai Ni and Kaga Kai Ni E, and result in a nonzero ASW value, which can cause unexpected mandatory ASW behaviour if, after considering ASW of all equipment, that the ASW requirement is met (she is not supposed to perform ASW, however after the ASW inheritance she might prioritize ASW).

**Screenshot and/or video**
[Source1: Twitter](https://twitter.com/Synobicort_SC/status/1298998245893394432)
[Source2: NGA](https://bbs.nga.cn/read.php?tid=23135246)

**Comment by Tibowl** [comment]
This issue has been [resolved](https://twitter.com/KanColle_STAFF/status/1299223283393466368) as of 2020-08-28
